import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  header: {
    justifyContent: 'center',
    alignItems: 'center',
    color: '#fff',
    gap: 15,
    flex: 1,
  },
  container: {
    padding: 15,
    backgroundColor: '#fff',
    gap: 10,
  },
  firstLetterContainer: {
    color: '#fff',
    height: 120,
    width: 120,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
    backgroundColor: '#63626c',
  },
    containerAccions: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: 60,
    gap: 10,
    marginBottom: 20,
  },
  accion: {
    backgroundColor: '#63626c',
    width: 90,
    height: 70,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 8,
    borderRadius: 10,
  },
  input: {
    height: 50,
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 15,
    paddingVertical: 0,
    backgroundColor: '#fff',
    color: '#63626c',
    fontSize: 20,
  },
  roleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  roleButton: {
    flex: 1,
    height: 50,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 5,
    backgroundColor: '#f9f9f9',
  },
  selectedRole: {
    backgroundColor: '#e0e0e0',
  },
  roleText: {
    fontSize: 16,
    color: '#000',
  },
  error: {
    color: 'red',
    marginBottom: 10,
    textAlign: 'left',
  },
  containerButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingLeft: 15,
    marginTop: 15,
    paddingEnd: 15,
  },
  map: {
    height: '100%',
    marginHorizontal: 'auto',
    borderRadius: 10,
    borderWidth: 1,
    width: '100%',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  modalContent: {
    width: '70%',
    borderRadius: 20,
    alignItems: 'center',
    backgroundColor: 'white',
    gap: 20,
  },
  modalTitle: {
    fontSize: 20,
    marginTop: 20,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  closeModal: {
    color: '#007BFF',
    marginBottom: 20,
  },
  buttonContainer: {
    alignItems: 'center',
    width: '100%',
  },
  butonImage: {
    borderBottomWidth: 0.5,
    borderTopWidth: 0.5,
    borderColor: '#63626c',
    width: '100%',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  confirmButton: {
    borderBottomWidth: 0.5,
    borderTopWidth: 0.5,
    borderColor: '#63626c',
    width: '100%',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButton: {
    padding: 10,
    borderRadius: 5,
    marginHorizontal: 10,
    width: '40%',
    alignItems: 'center',
  },
  buttonTextEliminar: {
    color: 'red',
    fontSize: 16,
  },
  buttonTextCancelar: {
    fontSize: 16,
    color: '#007BFF',
  },
  containerLocationInfo: {
    width: '100%',
    backgroundColor: '#f9f9f9',
    justifyContent: 'center',
    height: 250,
    position: 'relative',
  },
  weatherInfo: {
    width: 160,
    position: 'absolute',
    flexDirection: 'row',
    top: 5,
    left: 5,
    backgroundColor: 'rgb(255, 255, 255)',
    zIndex: 100,
    alignContent: 'center',
    justifyContent: 'space-evenly',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  weatherInfoMain: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  arrowLeft: {
    marginTop: 15,
    alignSelf: 'flex-start',
    paddingLeft: 15,
  },
});
