import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  header: {
    justifyContent: 'center',
    alignItems: 'center',
    color: '#fff',
    gap: 15,
  },
  container: {
    height: '67%',
    padding: 15,
    backgroundColor: '#fff',
    gap: 10,
  },
  firstLetterContainer: {
    color: '#fff',
    height: 120,
    width: 120,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
    backgroundColor: '#63626c',
  },
  containerAccions: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: 60,
    gap: 10,
  },
  accion: {
    backgroundColor: '#63626c',
    width: 90,
    height: 70,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 8,
    borderRadius: 10,
  },
  input: {
    height: 50,
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 15,
    backgroundColor: '#fff',
    color: '#63626c',
    fontSize: 20,
  },
  roleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  roleButton: {
    flex: 1,
    padding: 10,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    alignItems: 'center',
    marginHorizontal: 5,
    backgroundColor: '#f9f9f9',
  },
  selectedRole: {
    backgroundColor: '#e0e0e0',
  },
  roleText: {
    fontSize: 16,
    color: '#000',
  },
  error: {
    color: 'red',
    marginBottom: 10,
    textAlign: 'left',
  },
  buttonSave: {
    backgroundColor: '#63626c',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    width: 150,
    borderRadius: 10,
  },
  buttonCancel: {
    backgroundColor: '#e32424',
    height: 50,
    width: 150,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  containerButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: 60,
    gap: 10,
  },
  map: {
    height: 200,
    marginHorizontal: 'auto',
    borderRadius: 10,
    borderWidth: 1,
    width: '98%',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  modalContent: {
    width: '70%',
    borderRadius: 20,
    alignItems: 'center',
    backgroundColor: 'white',
    gap: 20,
  },
  modalTitle: {
    fontSize: 20,
    marginTop: 20,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  closeModal: {
    color: '#007BFF',
    marginBottom: 20,
  },
  buttonContainer: {
    alignItems: 'center',
    width: '100%',
  },
  butonImage: {
    borderBottomWidth: 0.5,
    borderTopWidth: 0.5,
    borderColor: '#63626c',
    width: '100%',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap:10,
  },
  confirmButton: {
    borderBottomWidth: 0.5,
    borderTopWidth: 0.5,
    borderColor: '#63626c',
    width: '100%',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButton: {
    padding: 10,
    borderRadius: 5,
    marginHorizontal: 10,
    width: '40%',
    alignItems: 'center',
  },
  buttonTextEliminar: {
    color: 'red',
    fontSize: 16,
  },
  buttonTextCancelar: {
    fontSize: 16,
    color: '#007BFF',
  },
});
